# Ansible connection properties
ssh_user: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_USER') }}"
ssh_pass: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_PASS') }}"
ansible_user: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_USER') }}"
ansible_become_password: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_PASS') }}"
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

# General properties
pd_prop_project_name: "<%= projectNameUpperCase %>"
pd_prop_service_name: "<%= serviceName %>"
pd_prop_project_version: "{{ lookup('ansible.builtin.env', 'PODMAN_PROJECT_VERSION') }}"
pd_prop_artifact_name: "{{ lookup('ansible.builtin.env', 'PODMAN_ARTIFACT_NAME') }}"
pd_prop_artifact_sha256: "{{ lookup('ansible.builtin.env', 'PODMAN_ARTIFACT_SHA256') }}"
pd_prop_build_number: "{{ lookup('ansible.builtin.env', 'PODMAN_BUILD_NUMBER') }}"
pd_prop_project_version_run: "{{ pd_prop_project_version }}-{{ pd_prop_build_number }}"

# Properties for creating directories
pd_prop_project_home: "/apps_ux/<%= projectNameUpperCase %>"
pd_prop_service_home: "/apps_ux/<%= projectNameUpperCase %>/<%= serviceName %>"
pd_prop_service_install_directory: "/apps_ux/<%= projectNameUpperCase %>/<%= serviceName %>/{{ pd_prop_project_version_run }}"
pd_prop_service_current_version: "/apps_ux/<%= projectNameUpperCase %>/<%= serviceName %>/current"
pd_prop_service_data: "/apps_data/<%= projectNameUpperCase %>/<%= serviceName %>"
pd_prop_service_logs: "/apps_ux/logs/<%= projectNameUpperCase %>/<%= serviceName %>"
pd_prop_service_s6_path: "/apps_ux/s6_services/<%= serviceName %>"

# Tomcat properties

# Webapp properties
